version: '3.8'

services:
  configserver:
    build: ./configserver
    container_name: configserver
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:8888/ || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
    hostname: configserver
    networks:
      - jenkins
  jenkins:
    build: ./jenkins
    container_name: jenkins
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      CASC_JENKINS_CONFIG: "/usr/share/jenkins/ref/jenkins.yaml"
    volumes:
      - "./jenkins/shared-lib:/tmp/shared-lib"
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
    links:
      - configserver

networks:
  jenkins:
    driver: bridge
