management.security.enabled: false
server.port: 8888
logging.file: configserver.log
spring.application.name: ConfigServer
spring.profiles.active: default
spring.cloud.config.server:
  git:
    uri: git@bitbucket.org:ggnanasekaran77/{application}.git
    ignoreLocalSshSettings: true
    strictHostKeyChecking: false
    force-pull: true
    searchPaths: conf
    timeout: 60
    privateKey: |
                    -----BEGIN RSA PRIVATE KEY-----
                    MIIEpAIBAAKCAQEAtuY1k5k1pzG1SIcfEahIOkM8pHqPIHcNUfdI3tegFGnmkfxJ
                    7DBkoxHJqPqvobj7c+RqRXL9Zm2L56y2L7em9fXzatthAQ/ypIMp4FxOiErvhEW/
                    0DO3edBxSu/EbGg4Km+V2+3jByZK0ecCattRhBVh+jW7khhS7qLqAuh+KLL7vcSe
                    x9Ke2NUJrEyeqnyL6iw4dSnueX2tS6Upxvm4nk6CyUXrGRzbExOSv1MmVoeDBvFf
                    YNfXUPPvfXtnvm3uPHqVEYu4/IXYSOcxRNEzvViS/sjcmgjGCBgKmZitd0ha7xde
                    fXhG1UGFd/vS81l71UyCzT3IIQ+6iMwfn0Xn7wIDAQABAoIBAQCVFVkekof1XMNT
                    9zAQCIe3Vg8cUvpPkDs/UL4JRuGpQhk7bdYju96MPXePUafPvyTX9pvZOD3tO+YK
                    VfG7O4vQeUaNF30ejI1QI8oCo7svxUUvIFuVrlIj7RAr8Py/EMSXcpVIy8N+lGvw
                    ZMjHqTXs4DEY7quSDlmrQwhUjoYnTTxKnRcLihuWLyUcraqysHKrAJUpkWNpBJNL
                    uPEMgbnC87hCNK/F1MuwPlYbjcmsrISQSpxkYUoC3CFZrapAWU3JsubNvqL11xdB
                    qbrC1M5JDBv2hj43aHFBEq2dsmMOyuN1oScCKWCiHakMESGip/aFwipbs80O89UW
                    LR71EObhAoGBAON5I/51AfHpTld00N4Usilny2k9Dl58VN7WazTD1d/0U8LjKrDL
                    EimS5QzwlS/eAC/JiTutW5WhKFh50fPT9OTtUx0lH1IEaho7/a19qRSdnemPeSo9
                    +boGkmSuAQguRgk0aA3EAsN19O3CPpxI/Ru8pHet4aEWGTs98weGXsxTAoGBAM3W
                    Dg2j84xAWR2yg9NKzl2MFMj1trXfyvRLuYWnSeyJ8PVGXifo7GFP+0Xoo8DJRscX
                    r7tZyUjkurhl1JBaUz6Lvlz8+np2LAzBDmmq08X18uEWqfp77IBfbjrmF0SrJO1q
                    iXQrwtOxMlq+pGaggBm4HmkZMki6fN7loDvgAqJ1AoGBANt6zTH9r8y8MazMt6Mw
                    EN9GmMuH789W44THGlWlBz25PwBxs4U1yuZ2J68eirPO3hs9t73u/MkY4BbOI7fB
                    sS8ZlfIvGVNHkyCQ9alp77RGiFEM7/nEJqpJIQMnqTM9grHq8OMnVwtFSvgFTef5
                    vM4AbChVi7ij2+B/W3jNO7alAoGAPyxdL86L5xWwxC6Pyv+AirF9h5fyNauzzHqZ
                    O+32AETt0TmBmFoiglNb2T7nUznzIROh+aw63MZmkEWgkZVHS0D0cfGqpn8yUc/G
                    rqOhT3aGzpJ4JMp38YZYfHc12Pt13+/8s8zihLozrCoqptzHtB0QKE11Y2DpBjgP
                    j5DW/ikCgYArfW2tK05HzGoMejZdgavx1WtOg0bWnnQTY5IaLZS0aezvtnW50GAi
                    KcaZBSAyePkov3pnlTasRlhYiN94V0spGm7NxOQXtRQHKOXaulbwpjcJvGrvK3oU
                    kTYKf34+ga9VJKnV42ydK+K04YTyWtjaqWehEbTB6CEFwwdhN+mbnQ==
                    -----END RSA PRIVATE KEY-----
management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true
    health.show-details: always
